from pathlib import Path
import json
rows='''runway-credits|Runway kredi ve saniye fiyatı|1 kredi $0,01; Gen-4.5 12 kredi/sn; Veo 3.1 sesli 40 kredi/sn.|17 Eylül 2026 resmi tabloda kontrol edildi. 8 sn için $0,96 ve $3,20; 10 shot ve iki denemede $19,20 ve $64. Diğer ücretler ayrıca.|D01,D03,D05|video-economics|verified
gex131|Hetzner GEX131 teklifleri|€889/ay; başka listede €1.199/ay + €599 setup; saatlik €1,4247. GEX44 €184–234/ay.|Vergi, tarih, ülke ve konfigürasyon eşitlenmeden tek fiyat sayılamaz. €1,4247 × 720 = €1.025,784. Güncel teklif bağımsız teyit edilmedi.|D06|gpu-economics|conflict
claude-max|Claude Max ve bireysel planlar|Claude Max $100/$200; ChatGPT Plus $20, Pro $100/$200, Business yaklaşık $25/kişi.|Kaynak fiyatları. İnsan aboneliği API kredisi veya 15 ajan için sınırsız otomasyon hakkı değildir.|D06|gpu-economics|source
gitclear|GitClear churn ve refactoring|600M+ satır; churn %84 artış; refactoring %25’ten %10 altına; copy/paste moved code’u geçiyor.|%84 bu revizyonda bağımsız teyit edilmedi. Korelasyon nedensellik değildir; güncel metodoloji churn’ü iki haftada yeniden yazılan/silinen satırlarla tanımlar.|D02,D04|measurement|source
swe-bench|SWE-bench aileleri ve model skorları|Özgün: 12 Python repo/2.294 issue; Verified: 500 problem; Pro: 41 repo/1.865 görev. Opus 5 %96–97, Sol %96,2, Fable/Mythos %93,9–95, Qwen 3.8 %67,7–77,3, Qwen2.5 32B %27–33; Pro Muse Spark %61,5, Fable %80.|Farklı harness ve benchmark’lar bir sıralamaya karıştırılmaz. Model adları ve güncel skorlar bağımsız teyit edilmedi; contamination imkânsız denemez.|D02,D04,D06|measurement|source
rpm|Faceless gelir ve RPM|Finans/AI/business için $7–25 RPM; başlangıç $100–500/ay; 12–18 ayda düşük binler, $10k+ azınlık, breakout 1–3 yıl.|Kaynak senaryosu, gelir garantisi değil. RPM üretici geliri; CPM reklamveren ölçümü. $500 gider için $7 RPM’de yaklaşık 71.429, $25 RPM’de 20.000 görüntülenme gerekir.|D05|video-economics|scenario
gpu-break-even|Self-host break-even çelişkisi|150M token/ay + %40 dolulukta self-host kazancı; ucuz API $0,14–0,28/M; ucuz modelde 120–180M, flagship’te 15–25M eşik.|150M × $0,28/M = $42; €889 GPU kira bedelini otomatik karşılamaz. 100 token/sn × 30 gün = 259,2M, %40’ta 103,68M. Kalite, input/output karışımı ve kur eksik.|D06|gpu-economics|corrected
veo-arithmetic|D05 Veo çarpım hatası|30 saniye × $0,75 için kaynakta $12 yazıyor.|Doğru çarpım $22,50. Bu hesap düzeltmesi, $0,75’in güncel fiyat olduğunu doğrulamaz.|D05|video-economics|corrected
api-flagship|Frontier API tarifeleri|Claude Opus 5 $5/$25, Fable 5.1 $10/$50, Sonnet 5 $2/$10, Haiku 4.5 $1/$5; Sol $4/$20 promosyon veya $5/$30, Astra $10/$50 (input/output, 1M token).|D06 kaynak tablosu; tarihler ve model isimleri bağımsız teyit edilmedi. Sol promosyonu 21 Kasım’a kadar iddia edilir. Cache ve batch fiyatı ayrı.|D06|gpu-economics|source
api-open|Açık model API fiyatları|DeepSeek Flash $0,14/$0,28; GLM $1/$3,41; Morph Kimi $3/$15; Qwen Next $0,11/$0,80 / 1M input/output.|Provider, bölge, veri politikası ve cache değişebilir. Tek “token fiyatı”na indirgenmez.|D06|gpu-economics|source
cache-batch|Cache ve batch tasarrufu|D02 prompt cache ile %90’a kadar; D06 batch %50 indirim, cache hit için temel fiyatın %10’u.|Sağlayıcı ve token sınıfına bağlı kaynak değerleri. Tüm faturada aynı indirim garanti değildir; cache yazma/TTL/uygun prefix ölçülür.|D02,D06|spec-context|source
openrouter|OpenRouter ücretleri|500+ model; kredi alımında %5,5; BYOK $25.000’e kadar ücretsiz sonra %5.|Kaynak tarihli iddialar. Gateway routing kolaylığı fiyat indirimi veya tüm provider’larda aynı retention demek değil.|D06|gpu-economics|source
m5-max|M5 Max yerel kapasite|40-core GPU, 128 GB, 600–614 GB/sn; Qwen3.5-35B-A3B 112 token/sn; Qwen3.6-27B yaklaşık 30 token/sn.|Donanım/benchmark kaynak iddiası; kişisel tek oturum ölçümü 15 eşzamanlı ajan SLA’sı değildir.|D06|local-models|source
gpu-hardware|GEX donanım profilleri|GEX44 RTX 4000 SFF Ada 20 GB; GEX131 RTX PRO 6000 Blackwell Max-Q 96 GB + Xeon Gold 5412U 24 core/256 GB DDR5.|Kaynak konfigürasyonu; sipariş öncesi güncel yapılandırma teyit edilmeli. KV cache ve concurrency ayrıca kapasite ister.|D06|gpu-economics|source
glm-fit|GLM toplam ve aktif parametre|GLM-5.2/5.3: 744B toplam, 40B aktif; 1M context; tek 96 GB kart tavsiyesi.|744B × 4 bit / 8 ≈ 372 GB yalnız ağırlık; aktif 40B toplam ağırlığı azaltmaz. Offload veya cluster olmadan sığma varsayımı tutmaz.|D06|local-models|corrected
qwen25|Qwen2.5-Coder bellek aralıkları|7B Q4 4,7–5,5 GB ve 40–50 tok/sn; 14B Q5 10,7–12,5 GB, Q8 14,7–16,5 GB; 32B Q4 19,6–22 GB.|Quantization, context, runtime ve donanımla değişir. Q8 kayıpsız değildir. 24 GB kartta ağırlık sığması uzun context kapasitesini garanti etmez.|D02|local-models|source
deepseek-r1|DeepSeek-R1 tam model ve distill|671B ana model, yaklaşık 400+ GB ve 8 H100; distill Qwen32B Q4 için 24 GB sınıfı.|Tam model ile distill aynı yetenek ve donanım maliyeti değildir; paralellik ve KV cache bütçesi eklenir.|D02|local-models|source
open-model-scores|Açık model yetenek iddiaları|Qwen3-Coder-Next 80B-A3B, 512 expert/10 seçili, 256K–1M context, ~46 GB, SWE %70,6; Qwen3.6-27B %77,2; DeepSeek V4 Pro %80,6, Flash 284B-A13B/2-bit ~39 tok/sn; Kimi K3 2,8T/ Vals %93,4; GLM Terminal-Bench 81,0.|Tarihli kaynak iddiaları; aynı görev/harness değildir. Gerçek artifact, lisans ve ölçüm kurulumunu teyit etmeden model sıralaması yapılmaz.|D06|local-models|source
serving-speed|Serving motoru hızları|vLLM H100’de 12.500 token/sn; SGLang %29 avantaj; Ollama 0.19 MLX ile decode 58→112, prefill 1.154→1.810.|Model, batch, context ve donanım eşitlenmeden kendi kullanımına taşınamaz. Toplam throughput ile kullanıcı başına hız ayrılır.|D06|local-models|source
kv-cache|KV cache büyüme iddiası|D02 bağlam büyüdükçe KV cache’in logaritmik arttığını söylüyor.|Sabit model mimarisi ve batch için yaklaşık doğrusal artış temel kapasite varsayımıdır; paged allocation toplam gerekli veriyi logaritmik yapmaz.|D02|local-models|corrected
metr-2025|METR 2025 deney sonucu|16 deneyimli geliştirici, 246 görev; AI ile %19 daha uzun süre; katılımcılar yaklaşık %20 hızlanma algılıyor.|Dar örneklemde gerçek sonuç doğrulama kaydında mevcut. Yeni görev/model/ekiplere evrensel oran olarak taşınmaz.|D02,D04|measurement|verified
metr-2026|METR 2026 hızlanma sinyali|%4–20 hızlanma yönünde ham sonuçlar.|Seçim yanlılığı ve değişen katılım güvenilir genel etki tahminini engelliyor; eski doğrulama kaydı V07 ayrıntıyı korur.|D04|measurement|corrected
dora|DORA kullanım ve sistem etkisi|D02 %90 AI kullanımı; AI güçlü ve zayıf mühendislik sistemlerini büyütür.|%90 bağımsız yeniden teyit edilmedi; amplifier yorumu önceki resmi kontrolle desteklenir. Her ekipte stability artışı demek değil.|D02,D04|measurement|source
sdd-case|SDD modernizasyon vakası|Bir staff engineer + dört ajan, dört kişilik ekibe göre yarı süre, %90 ilk kabul, 5,4× throughput; arXiv 2605.18461.|Tek vaka ve kaynak iddiası; bütün ekiplerin küçültülmesi için nedensel kanıt değildir.|D02|spec-context|source
context-study|Repo talimatı araştırmaları|Context dosyaları %20+ inference maliyeti, genel başarı artışı yok; başka çalışma 1.925 repo/2.303 CLAUDE.md.|Kaynak çalışma kapsamıyla yorumlanır. Kısa, işe yarayan domain kuralı ile uzun genel talimatı eşitleme.|D06|spec-context|source
agents-adoption|AGENTS.md ve standartlaşma|60k+ repo, Aralık 2025 AAIF katılımı; Claude için CLAUDE.md farkı.|Tarihli benimsenme iddiası; bütün araçların aynı dosyayı aynı kuralla okuduğunu göstermez.|D06|spec-context|source
review-metrics|AI review kıyasları|Qodo F1 %60,1; CodeRabbit precision %49,2; Greptile recall %82; DeepSource F1 %84,51; Bugbot ~90 sn/$1–1,50 review.|F1, precision, recall ve farklı veri kümeleri aynı sıralamada karşılaştırılamaz. Kendi PR’ında gerçek hata ve yanlış alarm ölçülür.|D02,D06|testing-review|source
review-prices|Kod yardımcısı ve review planları|Copilot $10/$39; Cursor $20/$60/$200; Tabnine $39/$59 yıllık; CodeRabbit $24/$48/$72 kişi-ay yıllık.|Kaynak fiyatları, güncel teklif değil. Kullanıcı, repo, kullanım kotası ve API ayrı incelenir.|D04,D06|testing-review|source
productivity|Görev bazında üretkenlik|Review yaklaşık %15; docs/completion %50’ye; tekrarlı işler %30–40’a kadar kazanım. 25 kişi × 2 saat = 50 saat/ay örneği.|Farklı çalışmaların tavan/ortalama değerleri; review ve rework çıkarılmadan net ROI hesaplanmaz.|D04|measurement|scenario
coding-capacity|Ajan concurrency ve tarihler|Codex v0.115/16 Mart altı subagent; Agents API 10 Eylül beta; Cursor 2.0/29 Ekim 2025 sekiz worktree; Claude nested seviye beş; Composer çoğu iş <30 sn.|Kaynak tarihli özellik iddiaları; ürün sürümü/planı bağımsız teyit edilmedi. 15 ajan kapasitesi için gerçek kota ve bütçe ölçülür.|D06|coding-agents|source
mcp-cost|MCP bağlam maliyeti|Sunucu başına 2–5k schema token; 3–5 aktif server önerisi; incelenen 20’nin 13’ü arşivlenmiş.|Sabit protokol maliyeti veya bütün ekosistem oranı değil. Gerektiğinde tool yükle, bakım durumunu ilgili repo için kontrol et.|D06|mcp|source
repo-stars|Tarihli GitHub yıldızları|D02 Aider 40k+; D06 Context7 62k, Playwright MCP 37,1k, n8n 45k; OpenClaw 3 Mart 250.829, karşılaştırılan React 243k/Linux 218k.|Kaynak anlık sayılarıdır; farklı tarihler karıştırılmaz. Popülerlik kalite, bakım, güvenlik veya benimsenme garantisi değil.|D02,D06|operations|source
openclaw-history|OpenClaw tarih ve ölçek|Kasım 2025 başlangıcı, 29 Ocak 2026 yeniden adlandırma, 50+ kanal; kurucunun PSPDFKit $800M geçmişi.|Kaynak tarihsel/biografik iddiaları bağımsız teyit edilmedi. Teknik seçim için yetki, izolasyon ve bakım daha ilgili.|D06|operations|source
n8n-mcp|n8n MCP yüzeyleri|Nisan 2026 instance-level preview; community n8n-mcp 2.000+ node.|Sürüm ve plan bazında teyit gerekir; dokümantasyon arama ile workflow yürütme aynı yetki değildir.|D06|mcp|source
python-speed|Python toolchain hızları|Ruff 10–100×; ty/Pyrefly karşılaştırmasında Django 578 ms / 16 sn.|Kaynak mikrobenchmark’ı, bütün projelerde aynı sonuç değil. Ruff type checker değildir; plugin uyumluluğu ayrıca test edilir.|D06|developer-toolchain|source
stitch|Stitch tasarım planı|19 Mart 2026 sürümü; ücretsiz 350 generation, sonsuz canvas ve MCP.|Kaynak ürün/plan iddiası; React/Vite hedefi açık olmalı. Next.js varsayılanı stack kararını değiştirmez.|D06|developer-toolchain|source
security-incidents|Ajan güvenliği olay oranları|Sentry DSN Agentjacking %85; 12 Haziran Tenet; OpenClaw <2026.1.29 RCE / ≥2026.2.21 önerisi; Codex branch injection düzeltmesi.|Tarihli kaynak olayları bağımsız reproduce edilmedi. Eski minimum sürüm bugünün güvenli sürüm garantisi değildir; güncel advisory kontrolü gerekir.|D06|security|source
owasp|OWASP kategori numaraları|D02 “2026” listesinde LLM03 Excessive Agency, LLM04 Supply Chain yazıyor.|Kontrol edilen resmi 2025 listesinde Supply Chain LLM03, Excessive Agency LLM06. Rapor doğrulanmamış 2026 sıralaması üretmez.|D02|security|corrected
video-prices|Video modelleri kaynak fiyatları|Kling $0,10/sn, Veo Fast $0,15/sn, Sora 2 $0,10/sn, Runway $0,12–0,15/sn, Wan/Grok $0,05/sn.|Model, gateway, audio, çözünürlük ve deneme sayısı eşitlenmeden sıralama olmaz; Sora yaşam döngüsü ayrıca V03 kaydında.|D05|video-economics|source
veo-limits|Veo 3.1 kaynak sınırları|4/6/8 sn; 9:16 ve 16:9; 720p/1080p, bazı yollarda 4K; İngilizce prompt; reference/first-last/extend/native audio.|Model ID, region ve endpoint bazında. Türkçe çıktının gerçek kalitesi ayrı pilot gerektirir.|D03|video-models|source
video-other-limits|Diğer video modelleri|Luma 10–15 sn sınıfı; MiniMax H3 4–15 sn, 768p/2K, 24fps; Kling 3.0/Omni native 4K iddiası.|Kaynak ürün kabiliyetleri; UI/API ve model sürümü eşit değil. Güncel erişim ve sözleşme ayrıca kontrol edilir.|D03,D05|video-models|source
open-video-hardware|Açık video modelleri donanımı|Wan 24–80 GB; Hunyuan 60–80 GB; LTX bazı 24 GB yolları; gelişmiş workflow 32 GB VRAM/100 GB disk.|32 GB/100 GB tüm ComfyUI kurulumlarının minimumu değildir. Model, quantization ve çözünürlük belirtilmeli.|D03,D05|video-models|source
video-research|Video araştırma ölçümleri|LTX H100’de 5 sn/24fps/768×512 çıktıyı 2 sn üretme; CogVideoX 10 sn/768×1360.|Research ölçümleri uçtan uca SLA değil; cold-start, queue, I/O ve encode eklenir.|D03|video-models|source
openmontage|OpenMontage kapsam iddiaları|12 hat, 52 araç, 500+ skill, 14+ video API, yedi boyutlu routing.|Kaynak iddiaları; ürün kapsamı ve bakım bağımsız teyit edilmedi. YAML/skill/adaptör yapısı PoC’de sınanır.|D01|video-agents|source
shortgpt|ShortGPT dil ve araç kapsamı|30+ dil; TinyDB, Python editing language, EdgeTTS/ElevenLabs ve Bing Image.|Dil listesi Türkçe kalite kanıtı değildir; bağımlılık bakımı ve görsel hakları kontrol edilir.|D01|video-agents|source
avatar-limits|Avatar katalogları ve limitler|HeyGen 175+ dil, 100 batch, 100+ avatar; Synthesia 160+ dil, 240+ avatar; free 10 dk/ay ve 9 avatar.|Farklı plan/katalog ve tarihler. Türkçe ve lip-sync için aynı metinle karşılaştırma gerekir.|D03,D05|avatar|source
avatar-prices|Avatar fiyatları|HeyGen Creator $29/ay yıllık, Avatar V API $0,05/sn=$3/dk; kullanıcı deneyimi $330/ay; Synthesia Starter ~$18/ay yıllık.|UI ve API faturası ayrıdır. $330 tek kullanıcının anekdotu; genellenmez.|D05|avatar|source
tts-numbers|Ses ve transkripsiyon sayıları|ElevenLabs v2 29 dil; Flash v2.5 32 dil/~75ms; free 10k karakter/ay; Scribe Türkçe 88M konuşmacı; OpenAI 11 voice; MiniMax speech-2.8 40 dil.|Dil/konuşmacı sayısı kalite puanı değil. Latency koşulu, model ve ses hakkı ayrı; Türkçe özel terimler test edilir.|D03,D05|voice-localization|source
remotion-license|Remotion lisans ve fiyat|Birey/≤3 çalışan ücretsiz koşulu; $25/seat veya $0,01/render, min $100/ay kaynak senaryosu.|Ücretsiz koşul resmi V09 kontrolünde ayrılmıştır; bütün fiyatlar yeniden teyit edilmedi. MIT varsayımı yapılmaz.|D03,D05|editing-finishing|source
render-prices|Cloud renderer fiyatları|Shotstack $0,30/dk PAYG, $39/ay abonelikte $0,20/dk; Creatomate $49–54/2.000 kredi, 720p dk~14 kredi; JSON2Video $49,95/200 dk Full HD, free600 kredi, 4K4×; Bannerbear $49/1.000 kredi; Plainly $69/50dk.|Kredi ve dakika eşdeğer değil; kaynak planları güncel teklif sayılmaz. Egress, concurrency ve render tekrarları ayrıca.|D05|editing-finishing|source
opus-api|OpusClip erişim çelişkisi|D03 public API/Pro/free trial, 30 req/dk/key; D05 API yalnız Business, Starter $15/ay.|Plan/endpoint/tarih uyuşmazlığı çözülmüş sayılmaz. API hakkı satın alma öncesi teyit edilmeli.|D03,D05|repurposing|conflict
clip-prices|Repurposing planları|Vizard Creator ~$14,50/ay yıllık, API ve 32+ dil; Ssemble $7,50/ay tüm planlarda API.|Kaynak fiyat ve erişim iddiaları. Analiz edilen dakika, üretilen klip ve API kotası ayrılır.|D05|repurposing|source
social-prices|Yayın gateway fiyatları|Blotato $29/ay/9 platform; Upload-Post $24 veya yıllık $16, free10 upload; Ayrshare $149 ve 30+ profil için ayrı fiyat; Postiz self-host free/cloud29; Mixpost $299 tek sefer.|Platform izinleri ortadan kalkmaz. Hesap/profil/marka başına maliyet ve gerçek API kapsamı güncel kontrol ister.|D05|publishing|source
youtube-quota|YouTube upload kota değişimi|D05 videos.insert1.600, D01 100 birim/çağrı aktarıyor.|17 Eylül resmi tablo: videos.insert ve search.list ayrı ayrı100 çağrı/gün; çağrı başına1 kota. Otomatik sayfa özetindeki eski1.600 ifadesi gövdeyle çelişiyor. Kanal upload limiti farklı; ~20/gün evrensel değil.|D01,D03,D05|publishing|corrected
tiktok-limit|TikTok init sınırı|Direct Post init 6 istek/dakika/access token; audit olmadan private kısıtı.|V04 resmi kontrolü korunur; creator info/consent ve yayın durum doğrulaması gerekli.|D03,D05|publishing|verified
instagram-limit|Instagram süre ve kota iddiaları|D05 evrensel 90 sn; D01 200/saat BUC ve 60 günlük token; review2–4 hafta.|Doğrulanan Facebook Login Reels yolu 3 sn–15 dk. Diğer sayılar endpoint/hesap bağlamı olmadan kapasite/SLA kabul edilmez.|D01,D03,D05|publishing|corrected
suno|Suno kullanım bedeli ve hakları|Pro $10/ay veya yıllık $8; free kişisel; ücretli dönemde üretime commercial use.|Kaynak koşulları. Ticari izin, telif koruması ve üçüncü kişiye karşı tazminat aynı değil.|D05|music-rights|source
stock-music|Epidemic / Artlist planları|Epidemic Creator $9,99/Pro16,99 yıllık; Pro’da 5M takipçi/$10M şirket sınırı; Artlist Social9,99, Pro/Max3kanal iddiası.|Kaynak sözleşme özeti güncel hukuk görüşü değil. Reklam, client work, whitelist ve abonelik sonrası yeni yayın ayrı kontrol edilir.|D05|music-rights|source
policy-dates|YouTube politika tarihi|D01 Temmuz 2026; D05 ve resmi kaynak 15 Temmuz 2025 inauthentic content güncellemesi.|2025 tarihi esas alınır. AI kullanımı tek başına tüm videoların demonetize olduğu anlamına gelmez.|D01,D05|provenance|corrected
platform-population|AI içerik ve kapatma sayıları|TikTok 1,3B (Kasım2025) ve 3B (Temmuz2026) etiket; YouTube16kanal35M abone; shadowban%90 iddiası.|Bağımsız teyit edilmedi. Etiket sayısı toplam AI hacmi veya erişim nedeni değil; nedensellik kurulamaz.|D01,D05|provenance|source
ai-act|AB AI Act tarih ve yaptırım|Kaynaklarda 2 Ağustos2026 genel yürürlük, €15M/%3 yaptırım.|V11 konsolide metin sağlayıcı/deployer ve geçiş tarihlerini ayırır; her medya/her ihlal için aynı tarih/ceza varsayılmaz.|D01,D03,D05|provenance|corrected
video-compute|Video GPU ve ölçek eşiği|H100 $2–2,70/saat; Wan $0,25–0,60/clip; ayda5.000 clip self-host eşiği.|İş yükü, kalite ve doluluk olmadan evrensel eşik değil. Bakım ve tekrar üretim eklenmeli.|D05|video-economics|scenario
video-storage|Depolama senaryosu|100 video/gün × 200MB =20GB final; work3–10× =60–200GB/gün.|Senaryo hesabı; master retention ve egress ayrıca. Hacim gerçek telemetry ile güncellenir.|D03|media-contracts|scenario
video-architectures|Üç video mimarisinin bütçeleri|A bütçe faceless $50–150/ay + kullanım, $0,20–1/video; B premium $300–800; C B2B $150–400.|Kaynak senaryoları; kabul/deneme, premium oranı ve insan emeği dahil olmadan taahhüt değil.|D05|video-formats|scenario
rollout-investment|Ekip yatırım senaryoları|5–10dev:3–8kişi-gün/$150–750/2–4hafta;25dev:15–30/$1k–3,5k/6–10hafta;25–50dev:40–90/$4k–15k+/3–6ay;regüle60–150+/4–9+ay.|Kaynak varsayımları; tek geliştiriciye veya kendi ekibine doğrudan fiyat biçmez. Baseline ile net tasarruf ölçülür.|D04|rollout|scenario
video-roadmap|Video programı ve benchmark|21 Eylül2026–Şubat2027; 20–50 benchmark sahnesi, 17 belirsizlik grubu, ~12gün rollout, platform review için8haftaya varan pay.|Plan önerisi ve tamponlar, teslimat SLA’sı değil. Paralel işler basitçe toplanmaz; ayrıntılı evreler rehberde.|D03|rollout|scenario
pilot|Ölçüm pilotu|2–4hafta baseline,5–10dev pilot;10–20video;15ajan7/24 hedefi.|Kaynak başlangıç senaryosu. Aynı görev türü, review maliyeti, ret ve başarısız işler ölçüme dahil.|D04,D05,D06|rollout|scenario
make-webhook|Make webhook kapasitesi|300 gelen webhook/10sn iddiası.|Plan ve endpoint bazında teyit gerekir. Paralel/sıralı yürütme ayrı seçenek; queue ve retry tasarlanır.|D03|orchestration|source
retry|Circuit breaker örnek eşiği|Beş hata/60sn; retry base×2^n+jitter.|Kaynak tasarım örneği; evrensel eşik değil. Retry-After, hata türü, bütçe ve DLQ/insan revizyon ayrımı gerekli.|D01|orchestration|scenario
vibe-kanban|Vibe Kanban yaşam döngüsü|Bloop kapanışı10Nisan2026, Apache community/fork ayrımı.|Kaynak iddiası; ürün hizmeti, açık repo ve fork bakımını ayrı kontrol et. Sırf isim var diye mevcut Pane’den geçiş önerilmez.|D06|agent-managers|source'''
claims=[]
for row in rows.splitlines():
 id,title,statement,assessment,docs,topic,status=row.split('|')
 claims.append(dict(id=id,title=title,statement=statement,assessment=assessment,documents=docs.split(','),topic=topic,status=status))
urls={'runway-credits':'https://docs.dev.runwayml.com/guides/pricing/','owasp':'https://genai.owasp.org/llm-top-10/','metr-2025':'https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/'}
for c in claims:
 if c['id'] in urls:c['url']=urls[c['id']]
Path('src/data/claims.json').write_text(json.dumps(claims,ensure_ascii=False,indent=2)+'\n')
print(len(claims),'sayısal kayıt')
