import { useEffect, useRef, useState } from 'react';
import { Dialog, Icon } from './components';
import { navigation, sections } from './data/report';
import { Article, CostPage, Overview, ToolsPage } from './pages';
import { SearchDialog, SourcesPage } from './Library';
import { useStoredIds } from './lib/storage';

function parseRoute() {const [id,query]=window.location.hash.replace(/^#\/?/,'').split('?');return {id:id||'overview',params:new URLSearchParams(query||'')};}
export default function App() {
 const [route,setRoute]=useState(parseRoute);const [search,setSearch]=useState(false);const [menu,setMenu]=useState(false);const main=useRef<HTMLElement>(null);const saved=useStoredIds('futuristic:read:v1',sections.map(s=>s.id));const nav=navigation.find(n=>n.id===route.id);const section=sections.find(s=>s.id===route.id);
 useEffect(()=>{const change=()=>{setRoute(parseRoute());setMenu(false);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{document.title=`${nav?.label||'Sayfa bulunamadı'} — futuristic`;window.scrollTo({top:0,behavior:'instant'});const heading=main.current?.querySelector<HTMLElement>('h1');heading?.focus({preventScroll:true});},[route.id,nav?.label]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(x=>!x);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const links=(mobile=false)=><nav aria-label={mobile?'Bölüm seçimi':'Rapor bölümleri'}>{navigation.map((item,index)=><a href={`#/${item.id}`} aria-current={route.id===item.id?'page':undefined} className={`nav-link ${route.id===item.id?'active':''} ${index===1?'group-start':''}`} key={item.id}><Icon name={item.icon} size={19}/><span>{item.label}</span>{saved.ids.includes(item.id)?<Icon name="check" size={14}/>:item.number&&<small>{item.number}</small>}</a>)}</nav>;
 return <div className="app-shell"><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();main.current?.focus();}}>İçeriğe geç</a><aside className="sidebar"><a href="#/overview" className="brand" aria-label="futuristic ana sayfa"><span className="brand-logo"><span>f</span><i/></span><span>futuristic<span className="brand-dot">.</span></span></a><div className="workspace-label"><span className="status-dot"/> RESEARCH ATLAS <span>v1.0</span></div><button className="sidebar-search" onClick={()=>setSearch(true)} aria-label="Araştırmada ara"><Icon name="search" size={17}/><span>Araştırmada ara</span><kbd>⌘ K</kbd></button><span className="sidebar-eyebrow">KEŞFET</span>{links()}<div className="sidebar-bottom"><div className="sidebar-reading"><div><span>Okuma yolculuğun</span><strong>{saved.ids.length}/{sections.length}</strong></div><progress className="progress" max={sections.length} value={saved.ids.length} aria-label="Okuma ilerlemesi"/></div><a href={`${import.meta.env.BASE_URL}rapor.md`} download className="sidebar-download"><Icon name="download" size={18}/><span>Raporu indir</span><small>MD</small></a><div className="sidebar-signature"><span className="avatar-placeholder">İK</span><span>İsmail Karaca<small>Araştırma koleksiyonu</small></span><Icon name="sparkles" size={17}/></div></div></aside>
 <div className="main-shell"><header className="topbar"><a className="mobile-brand" href="#/overview">futuristic<span>.</span></a><div className="breadcrumb"><span>Araştırma atlası</span><Icon name="chevron" size={14}/><strong>{nav?.label||'404'}</strong></div><div className="topbar-actions"><span className="date-label"><span className="status-dot"/> 16 Eylül 2026</span><button className="btn btn-ghost btn-square" aria-label="Araştırmada ara" onClick={()=>setSearch(true)}><Icon name="search" size={19}/></button><a className="btn btn-ghost btn-square" href={`${import.meta.env.BASE_URL}rapor.md`} download aria-label="Raporu Markdown olarak indir"><Icon name="download" size={19}/></a></div></header><main id="main" className={`main-content page-${route.id}`} ref={main} tabIndex={-1}>{route.id==='overview'?<Overview read={saved.ids}/>:section?<Article key={section.id} section={section} read={saved.ids.includes(section.id)} onRead={()=>saved.toggle(section.id)} persisted={saved.persisted}/>:route.id==='tools'?<ToolsPage key={route.params.get('tool')||'all'} initialTool={route.params.get('tool')||undefined}/>:route.id==='cost'?<CostPage/>:route.id==='sources'?<SourcesPage params={route.params}/>:<div className="not-found"><span className="eyebrow">404 / KAYBOLAN BİR FİKİR</span><h1 tabIndex={-1}>Bu bölüm bulunamadı.</h1><p>Araştırma atlasından devam edebilirsin.</p><a href="#/overview" className="btn btn-primary">Genel bakışa dön <Icon name="arrow"/></a></div>}<footer className="site-footer"><span>futuristic<span className="brand-dot">.</span><small>Meraktan, uygulamaya.</small></span><a href="#/methodology">Kaynaklarla desteklenen, insan odaklı araştırma <Icon name="arrow" size={14}/></a><span className="mono">2026 / 001</span></footer></main></div>
 <nav className="mobile-dock" aria-label="Mobil gezinme"><a href="#/overview" aria-current={route.id==='overview'?'page':undefined}><Icon name="grid"/><span>Genel bakış</span></a><button onClick={()=>setMenu(true)} aria-expanded={menu}><Icon name="book"/><span>Bölümler</span></button><a href="#/tools" aria-current={route.id==='tools'?'page':undefined}><Icon name="boxes"/><span>Araçlar</span></a><a href="#/sources" aria-current={route.id==='sources'?'page':undefined}><Icon name="library"/><span>Kaynaklar</span></a></nav>
 {menu&&<Dialog title="Araştırma bölümleri" onClose={()=>setMenu(false)}><div className="mobile-menu">{links(true)}</div><p className="fine-print">{saved.ids.length} / {sections.length} bölüm okundu · Bu tarayıcıda saklanır.</p></Dialog>}{search&&<SearchDialog onClose={()=>setSearch(false)}/>}</div>;
}
